#!/bin/bash
# Randomly choose 10 words from dictionary for typing training,
# and then show typing errors if any.
# Use './type.sh -r' to re-type last time's 10 words
# Use 'time ./type.sh' to roughly measure your typing speed
# Try '(time ./type.sh) 2>&1| tee tt.report; ./score.sh' for scoring further
# Use './type.sh -f' to type a fixed sentence ONLY

# This script is generated by DeepSeek on prompts of merging two
# manually-written branches of my demonstration script posted on GitHub.
# DS jumps over a human in this job.

DICT_FILE='/usr/share/dict/words'
TOTYPE_FILE='./totype.sav.txt'
TYPED_FILE='./typed.sav.txt'
FIXED_SENTENCE='The quick brown Fox, jumps over a lazy Dog.'
PUNCT_STR="...,,,,-\";:!"  # define your own punctuation list here

rm $TYPED_FILE 2> /dev/null

if [ "$1" == "-f" ] ; then
    echo $FIXED_SENTENCE > $TOTYPE_FILE
    typing_times=1
else 
    if [ "$1" != "-r" ] || [ ! -f $TOTYPE_FILE ] ; then
        rm $TOTYPE_FILE 2> /dev/null
        
        if [ "$1" == "-f" ] ; then
            # This case is handled above, but keeping structure
            :
        else
            words_total=$(wc -l $DICT_FILE | cut -f1 -d" ")
            found_quote=0
            words_needed=10
            
            for ((i=0; i<$words_needed; i++)); do
                # Use better random number generation from second branch
                rand_num=$(expr '(' $RANDOM '*' $RANDOM '+' $RANDOM ')' % $words_total '+' '1')
                rand_word="$(head -n$rand_num $DICT_FILE | tail -n1)"
                
                # Filter out accented characters (from second branch)
                if [[ $(echo $rand_word | grep -P "[\x80-\xff]") ]]; then
                    printf "$rand_word in dictionary skipped (accented characters)\n" >&2
                    let i=$i-1
                    continue
                fi
                
                # Filter excessive quotes (from second branch)
                if [[ $rand_word =~ \' ]]; then
                    let found_quote=$found_quote+1
                    if [[ $found_quote -gt 3 ]] ; then
                        printf "$rand_word in dictionary skipped (too many quotes)\n" >&2
                        let i=$i-1
                        continue
                    fi
                fi
                
                # Add punctuation with probability (from second branch)
                rn=$RANDOM
                if [ $rn -gt 27000 ]; then  # punctuation possibility=(32767-27000)/32768 ≈ 17.6%
                    punct_pos=$(expr $rn % ${#PUNCT_STR})
                    punct_char=${PUNCT_STR:$punct_pos:1}
                    rand_word=$(echo ${rand_word}${punct_char})
                fi
                
                echo $rand_word >> $TOTYPE_FILE
            done
        fi
    fi
    typing_times=$(wc -l $TOTYPE_FILE 2>/dev/null | cut -f1 -d" " || echo 10)
fi

# Type the words/sentence
for ((i=1; i<$typing_times+1; i++)); do
    echo "${i}#####    $(sed -n "${i}p" $TOTYPE_FILE)"
    echo -n "${i}typing>>>"
    read key_in
    echo $key_in >> $TYPED_FILE
done

# Show differences
if [ $typing_times != 1 ] ; then
    diff_options='-y -W60 --suppress-common-lines'
else
    diff_options=''
fi

echo
echo "Error(s) found by diff:"
diff_output=$(diff $diff_options $TOTYPE_FILE $TYPED_FILE 2>/dev/null)
if [ $? -eq 0 ]; then
    echo "No errors! Excellent typing!"
else
    echo "$diff_output"
fi

# can use vimdiff for visual comparing
